ERROR:__mp_main__.lightning_ticker_FX_BTC_JPY:Handshake status 429 Too Many Requests
Traceback (most recent call last):
  File "C:\Users\hks-s\Anaconda3\lib\site-packages\websocket\_app.py", line 292, in run_forever
    self.sock.connect(
  File "C:\Users\hks-s\Anaconda3\lib\site-packages\websocket\_core.py", line 252, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "C:\Users\hks-s\Anaconda3\lib\site-packages\websocket\_handshake.py", line 79, in handshake
    status, resp = _get_resp_headers(sock)
  File "C:\Users\hks-s\Anaconda3\lib\site-packages\websocket\_handshake.py", line 164, in _get_resp_headers
    raise WebSocketBadStatusException("Handshake status %d %s", status, status_message, resp_headers)
websocket._exceptions.WebSocketBadStatusException: Handshake status 429 Too Many Requests
WARNING:__mp_main__.lightning_ticker_FX_BTC_JPY:closed
INFO:__mp_main__.lightning_ticker_FX_BTC_JPY:open
INFO:__mp_main__.lightning_ticker_FX_BTC_JPY:Writing to: ~/btc\lightning_ticker_FX_BTC_JPY\stream\2021-03-05.txt
ERROR:__mp_main__.lightning_ticker_FX_BTC_JPY:
Traceback (most recent call last):
  File "C:\Users\hks-s\Anaconda3\lib\site-packages\websocket\_app.py", line 349, in run_forever
    dispatcher.read(self.sock.sock, read, check)
  File "C:\Users\hks-s\Anaconda3\lib\site-packages\websocket\_app.py", line 69, in read
    r = self.select()
  File "C:\Users\hks-s\Anaconda3\lib\site-packages\websocket\_app.py", line 80, in select
    r, w, e = select.select((sock, ), (), (), self.ping_timeout)
KeyboardInterrupt
